sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  - composer
  - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest PHP_REDIS=enabled
    - php: 7.0
      env: WP_VERSION=latest PHP_REDIS=enabled
    - php: 5.6
      env: WP_VERSION=latest PHP_REDIS=enabled
    - php: 5.6
      env: WP_VERSION=latest PHP_REDIS=disabled
    - php: 5.6
      env: WP_VERSION=latest PHP_REDIS=disabled WP_REDIS_USE_CACHE_GROUPS=true
    - php: 5.6
      env: WP_VERSION=latest PHP_REDIS=enabled WP_REDIS_USE_CACHE_GROUPS=true
    - php: 5.6
      env: WP_VERSION=nightly PHP_REDIS=enabled
    - php: 5.6
      env: WP_TRAVISCI=phpcs
    - php: 5.3
      env: WP_VERSION=latest PHP_REDIS=enabled

services:
    - redis-server

before_script:
    - |
      if [[ ! -z "$WP_VERSION" ]] ; then
        bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      fi
    - |
      if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
        export PATH="$HOME/.composer/vendor/bin:$PATH"
        composer global require wp-coding-standards/wpcs
        phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
      fi

script:
    - |
      if [[ ! -z "$WP_VERSION" ]] ; then
        if [[ "$PHP_REDIS" == "enabled" ]] ; then
          echo 'extension = "redis.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        fi
        phpunit
        phpunit -c multisite.xml
      fi
    - |
      if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
        phpcs
      fi
