sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  - composer
  - $HOME/.composer/cache

matrix:
  include:
    - php: 7.4
      env: WP_VERSION=latest PHP_REDIS=enabled
    - php: 7.4
      env: WP_TRAVISCI=phpcs
    - php: 7.3
      env: WP_VERSION=nightly PHP_REDIS=enabled
    - php: 7.3
      env: WP_VERSION=latest PHP_REDIS=enabled
    - php: 7.3
      env: WP_VERSION=latest PHP_REDIS=disabled
    - php: 7.3
      env: WP_VERSION=latest PHP_REDIS=disabled WP_REDIS_USE_CACHE_GROUPS=true
    - php: 7.3
      env: WP_VERSION=latest PHP_REDIS=enabled WP_REDIS_USE_CACHE_GROUPS=true
    - php: 7.2
      env: WP_VERSION=latest PHP_REDIS=enabled

services:
    - redis-server

before_script:
    - export PATH="$HOME/.composer/vendor/bin:$HOME/.config/composer/vendor/bin:$PATH"
    - composer install
    - |
      if [[ ! -z "$WP_VERSION" ]] ; then
        bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      fi

script:
    - |
      if [[ ! -z "$WP_VERSION" ]] ; then
        if [[ "$PHP_REDIS" == "enabled" ]] ; then
          echo 'extension = "redis.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
          redis-server --version
        fi
        composer test
        WP_MULTISITE=1 composer test
      fi
    - |
      if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
        composer lint
      fi
