language: php

php:
    - 5.3
    - 5.5

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=3.6 WP_MULTISITE=0

before_script:
    - bash bin/install-redis.sh
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit
